CS318 - Pintos: src/tests/arc4.h File Reference
arc4.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct arc4
Alleged RC4 algorithm encryption state.
Functions
void arc4_init (struct arc4 *, const void *, size_t)
void arc4_crypt (struct arc4 *, void *, size_t)
tests/arc4.h
Function Documentation
arc4_crypt()
void arc4_crypt (struct arc4 * , void * , size_t)
tests/arc4.h
Definition at line 35 of file arc4.c.
References buf, arc4::i, arc4::j, arc4::s, s, ustar_header::size, and swap_byte().
Referenced by init(), main(), and test_main().
arc4_init()
void arc4_init (struct arc4 * , const void * , size_t)
Definition at line 14 of file arc4.c.
References arc4::i, arc4::j, arc4::s, s, ustar_header::size, and swap_byte().
Referenced by init(), main(), and test_main().