CS318 - Pintos: src/tests/userprog/boundary.h File Reference
boundary.h File Reference
Functions
void * get_boundary_area (void)
Returns the beginning of a page.
char * copy_string_across_boundary (const char *)
Returns a copy of SRC split across the boundary between two pages.
void * get_bad_boundary (void)
tests/userprog/boundary.h
Function Documentation
copy_string_across_boundary()
char* copy_string_across_boundary (const char *)
Returns a copy of SRC split across the boundary between two pages.
Definition at line 29 of file boundary.c.
References get_boundary_area(), strlcpy(), and strlen().
Referenced by test_main().
get_bad_boundary()
void* get_bad_boundary (void)
tests/userprog/boundary.h
tests/userprog/boundary.h
Used to position information such that the first byte of the information is valid, but not all the information is valid.
Definition at line 42 of file boundary.c.
References ROUND_UP.
Referenced by test_main().
get_boundary_area()
void* get_boundary_area (void)
Returns the beginning of a page.
There are at least 2048 modifiable bytes on either side of the pointer returned.
Definition at line 18 of file boundary.c.
References ROUND_UP.
Referenced by copy_string_across_boundary(), and test_main().