CS318 - Pintos: src/tests/vm/child-qsort-mm.c File Reference
child-qsort-mm.c File Reference
#include <debug.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
#include "tests/vm/qsort.h"
Functions
int main (int argc UNUSED, char *argv[])
Variables
const char * test_name = "child-qsort-mm"
Mmaps a 128 kB file "sorts" the bytes in it, using quick sort, a multi-pass divide and conquer algorithm.
Function Documentation
main()
int main (int argc UNUSED, char * argv[])
Definition at line 13 of file child-qsort-mm.c.
References CHECK, MAP_FAILED, mmap(), open(), qsort_bytes(), and quiet.
Variable Documentation
test_name
const char* test_name = "child-qsort-mm"
Mmaps a 128 kB file "sorts" the bytes in it, using quick sort, a multi-pass divide and conquer algorithm.
Child process for syn-read test.
Definition at line 10 of file child-qsort-mm.c.