CS318 - Pintos: src/tests/userprog/child-rox.c File Reference
child-rox.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <syscall.h>
#include "tests/lib.h"
Functions
static void try_write (void)
int main (int argc UNUSED, char *argv[])
Variables
const char * test_name = "child-rox"
Child process run by rox-child and rox-multichild tests.
Function Documentation
main()
int main (int argc UNUSED, char * argv[])
Definition at line 32 of file child-rox.c.
References atoi(), CHECK, exec(), fail(), isdigit(), msg(), quiet, snprintf(), try_write(), and wait().
try_write()
static void try_write (void) static
Definition at line 16 of file child-rox.c.
References buffer, CHECK, close(), open(), quiet, and write().
Referenced by main().
Variable Documentation
test_name
const char* test_name = "child-rox"
Child process run by rox-child and rox-multichild tests.
Child process for syn-read test.
Opens and tries to write to its own executable, verifying that that is disallowed. Then recursively executes itself to the depth indicated by the first command-line argument.
Definition at line 13 of file child-rox.c.