CS318 - Pintos: src/examples/cp.c File Reference
cp.c File Reference
#include <stdio.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
cat.c
Function Documentation
main()
int main (int argc , char * argv[])
cat.c
Copies one file to another.
Definition at line 9 of file cp.c.
References buffer, create(), EXIT_FAILURE, EXIT_SUCCESS, filesize(), open(), printf(), read(), and write().