CS318 - Pintos: src/tests/filesys/extended/dir-open.c File Reference
dir-open.c File Reference
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Opens a directory, then tries to write to it, which must fail.
Function Documentation
test_main()
void test_main (void)
Opens a directory, then tries to write to it, which must fail.
tests/main.h
Definition at line 9 of file dir-open.c.
References CHECK, mkdir(), msg(), open(), and write().