CS318 - Pintos: src/filesys/file.c File Reference
file.c File Reference
#include "filesys/file.h"
#include <debug.h>
#include "filesys/inode.h"
#include "threads/malloc.h"
Data Structures
struct file
An open file.
Functions
struct file * file_open (struct inode *inode)
Opens a file for the given INODE, of which it takes ownership, and returns the new file.
struct file * file_reopen (struct file *file)
Opens and returns a new file for the same inode as FILE.
void file_close (struct file *file)
Closes FILE.
struct inode * file_get_inode (struct file *file)
Returns the inode encapsulated by FILE.
off_t file_read (struct file *file, void *buffer, off_t size)
Reads SIZE bytes from FILE into BUFFER, starting at the file's current position.
off_t file_read_at (struct file *file, void *buffer, off_t size, off_t file_ofs)
Reads SIZE bytes from FILE into BUFFER, starting at offset FILE_OFS in the file.
off_t file_write (struct file *file, const void *buffer, off_t size)
Writes SIZE bytes from BUFFER into FILE, starting at the file's current position.
off_t file_write_at (struct file *file, const void *buffer, off_t size, off_t file_ofs)
Writes SIZE bytes from BUFFER into FILE, starting at offset FILE_OFS in the file.
void file_deny_write (struct file *file)
Prevents write operations on FILE's underlying inode until file_allow_write() is called or FILE is closed.
void file_allow_write (struct file *file)
Re-enables write operations on FILE's underlying inode.
off_t file_length (struct file *file)
Returns the size of FILE in bytes.
void file_seek (struct file *file, off_t new_pos)
Sets the current position in FILE to NEW_POS bytes from the start of the file.
off_t file_tell (struct file *file)
Returns the current position in FILE as a byte offset from the start of the file.
Function Documentation
file_allow_write()
void file_allow_write (struct file * file)
Re-enables write operations on FILE's underlying inode.
(Writes might still be denied by some other file that has the same inode open.)
Definition at line 133 of file file.c.
References ASSERT, file::deny_write, file::inode, inode_allow_write(), and NULL.
Referenced by file_close().
file_close()
void file_close (struct file * file)
Closes FILE.
Definition at line 46 of file file.c.
References file_allow_write(), free(), file::inode, inode_close(), and NULL.
Referenced by free_map_close(), fsutil_append(), fsutil_cat(), fsutil_extract(), and load().
file_deny_write()
void file_deny_write (struct file * file)
Prevents write operations on FILE's underlying inode until file_allow_write() is called or FILE is closed.
Preventing writes.
Definition at line 119 of file file.c.
References ASSERT, file::deny_write, file::inode, inode_deny_write(), and NULL.
file_get_inode()
struct inode* file_get_inode (struct file * file)
Returns the inode encapsulated by FILE.
Definition at line 58 of file file.c.
References file::inode.
file_length()
off_t file_length (struct file * file)
Returns the size of FILE in bytes.
filesys/file.h
Definition at line 145 of file file.c.
References ASSERT, file::inode, inode_length(), and NULL.
Referenced by fsutil_append(), load(), and validate_segment().
file_open()
struct file* file_open (struct inode * inode)
Opens a file for the given INODE, of which it takes ownership, and returns the new file.
Opening and closing files.
Returns a null pointer if an allocation fails or if INODE is null.
Definition at line 18 of file file.c.
References calloc(), file::deny_write, free(), file::inode, inode_close(), NULL, and file::pos.
Referenced by file_reopen(), filesys_open(), free_map_create(), and free_map_open().
file_read()
off_t file_read (struct file * file, void * buffer, off_t size)
Reads SIZE bytes from FILE into BUFFER, starting at the file's current position.
Reading and writing.
Returns the number of bytes actually read, which may be less than SIZE if end of file is reached. Advances FILE's position by the number of bytes read.
Definition at line 69 of file file.c.
References buffer, file::inode, inode_read_at(), and file::pos.
Referenced by fsutil_append(), fsutil_cat(), load(), and load_segment().
file_read_at()
off_t file_read_at (struct file * file, void * buffer, off_t size, off_t file_ofs)
Reads SIZE bytes from FILE into BUFFER, starting at offset FILE_OFS in the file.
Returns the number of bytes actually read, which may be less than SIZE if end of file is reached. The file's current position is unaffected.
Definition at line 82 of file file.c.
References buffer, file::inode, and inode_read_at().
file_reopen()
struct file* file_reopen (struct file * file)
Opens and returns a new file for the same inode as FILE.
Returns a null pointer if unsuccessful.
Definition at line 39 of file file.c.
References file_open(), file::inode, and inode_reopen().
file_seek()
void file_seek (struct file * file, off_t new_pos)
Sets the current position in FILE to NEW_POS bytes from the start of the file.
File position.
Definition at line 154 of file file.c.
References ASSERT, NULL, and file::pos.
Referenced by load(), and load_segment().
file_tell()
off_t file_tell (struct file * file)
Returns the current position in FILE as a byte offset from the start of the file.
Definition at line 164 of file file.c.
References ASSERT, NULL, and file::pos.
Referenced by fsutil_cat().
file_write()
off_t file_write (struct file * file, const void * buffer, off_t size)
Writes SIZE bytes from BUFFER into FILE, starting at the file's current position.
Returns the number of bytes actually written, which may be less than SIZE if end of file is reached. (Normally we'd grow the file in that case, but file growth is not yet implemented.) Advances FILE's position by the number of bytes read.
Definition at line 95 of file file.c.
References buffer, file::inode, inode_write_at(), and file::pos.
Referenced by fsutil_extract().
file_write_at()
off_t file_write_at (struct file * file, const void * buffer, off_t size, off_t file_ofs)
Writes SIZE bytes from BUFFER into FILE, starting at offset FILE_OFS in the file.
Returns the number of bytes actually written, which may be less than SIZE if end of file is reached. (Normally we'd grow the file in that case, but file growth is not yet implemented.) The file's current position is unaffected.
Definition at line 110 of file file.c.
References buffer, file::inode, and inode_write_at().