CS318 - Pintos: src/filesys/fsutil.h File Reference
fsutil.h File Reference
Functions
void fsutil_ls (char **argv)
void fsutil_cat (char **argv)
Prints the contents of file ARGV[1] to the system console as hex and ASCII.
void fsutil_rm (char **argv)
Deletes file ARGV[1].
void fsutil_extract (char **argv)
void fsutil_append (char **argv)
filesys/fsutil.h
Function Documentation
fsutil_append()
void fsutil_append (char ** argv)
filesys/fsutil.h
filesys/fsutil.h
The first call to this function will write starting at the beginning of the scratch device. Later calls advance across the device. This position is independent of that used for fsutil_extract(), so ‘extract’ should precede all `append's.
Definition at line 167 of file fsutil.c.
References block_get_role(), BLOCK_SCRATCH, BLOCK_SECTOR_SIZE, block_size(), block_write(), buffer, file_close(), file_length(), file_name, file_read(), filesys_open(), free(), malloc(), memset(), NULL, PANIC, printf(), PROTd, block::size, ustar_make_header(), and USTAR_REGULAR.
Referenced by run_actions().
fsutil_cat()
void fsutil_cat (char ** argv)
Prints the contents of file ARGV[1] to the system console as hex and ASCII.
Definition at line 34 of file fsutil.c.
References buffer, file_close(), file_name, file_read(), file_tell(), filesys_open(), hex_dump(), NULL, PAL_ASSERT, palloc_free_page(), palloc_get_page(), PANIC, PGSIZE, file::pos, and printf().
Referenced by run_actions().
fsutil_extract()
void fsutil_extract (char ** argv)
fsutil_ls()
void fsutil_ls (char ** argv)
fsutil_rm()
void fsutil_rm (char ** argv)
Deletes file ARGV[1].
Definition at line 61 of file fsutil.c.
References file_name, filesys_remove(), PANIC, and printf().
Referenced by run_actions().