CS318 - Pintos: src/tests/filesys/extended/grow-sparse.c File Reference
grow-sparse.c File Reference
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
tests/main.h
Variables
static char buf [76543]
Tests that seeking past the end of a file and writing will properly zero out the region in between.
Function Documentation
test_main()
void test_main (void)
tests/main.h
tests/main.h
tests/main.h
This must fail, because that directory is non-empty.
tests/main.h
This must fail.
tests/main.h
and an ordinary file in each of them, until we fill up the disk.
Then delete most of them, for two reasons. First, "tar" limits file names to 100 characters (which could be extended to 256 without much trouble). Second, a full disk has no room for the tar archive.
Definition at line 11 of file grow-sparse.c.
References buf, CHECK, check_file(), close(), create(), file_name, msg(), open(), seek(), and write().
Variable Documentation
buf
char buf[76543] static
Tests that seeking past the end of a file and writing will properly zero out the region in between.
Definition at line 8 of file grow-sparse.c.
Referenced by test_main().