CS318 - Pintos: src/examples/hex-dump.c File Reference
hex-dump.c File Reference
#include <stdio.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
hex-dump.c
Function Documentation
main()
int main (int argc , char * argv[])
hex-dump.c
Prints files specified on command line to the console in hex.
Definition at line 9 of file hex-dump.c.
References buffer, close(), EXIT_FAILURE, EXIT_SUCCESS, hex_dump(), open(), printf(), read(), and tell().