CS318 - Pintos: src/lib/kernel/stdio.h File Reference
stdio.h File Reference
Functions
void putbuf (const char *, size_t)
lib/kernel/stdio.h
Function Documentation
putbuf()
void putbuf (const char * buffer, size_t n)
lib/kernel/stdio.h
lib/kernel/stdio.h
Definition at line 153 of file console.c.
References acquire_console(), buffer, putchar_have_lock(), and release_console().