CS318 - Pintos: src/examples/mcat.c File Reference
mcat.c File Reference
#include <stdio.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
mcat.c
Function Documentation
main()
int main (int argc , char * argv[])
mcat.c
Prints files specified on command line to the console, using mmap.
Definition at line 10 of file mcat.c.
References EXIT_FAILURE, EXIT_SUCCESS, filesize(), MAP_FAILED, mmap(), munmap(), open(), printf(), STDOUT_FILENO, and write().