CS318 - Pintos: src/examples/mcp.c File Reference
mcp.c File Reference
#include <stdio.h>
#include <string.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
mcp.c
Function Documentation
main()
int main (int argc , char * argv[])
mcp.c
Copies one file to another, using mmap.
Definition at line 10 of file mcp.c.
References create(), EXIT_FAILURE, EXIT_SUCCESS, filesize(), MAP_FAILED, memcpy(), mmap(), munmap(), open(), and printf().