CS318 - Pintos: src/tests/filesys/extended/mk-tree.h File Reference
mk-tree.h File Reference
Functions
void make_tree (int at, int bt, int ct, int dt)
tests/filesys/extended/mk-tree.h
Function Documentation
make_tree()
void make_tree (int at, int bt, int ct, int dt)
tests/filesys/extended/mk-tree.h
Definition at line 12 of file mk-tree.c.
References CHECK, close(), do_mkdir(), do_touch(), msg(), open(), quiet, and snprintf().
Referenced by test_main().