CS318 - Pintos: src/tests/vm/mmap-remove.c File Reference
mmap-remove.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/vm/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Deletes and closes file that is mapped into memory and verifies that it can still be read through the mapping.
Function Documentation
test_main()
void test_main (void)
Deletes and closes file that is mapped into memory and verifies that it can still be read through the mapping.
tests/main.h
Definition at line 11 of file mmap-remove.c.
References CHECK, close(), create(), fail(), arc4::i, MAP_FAILED, memcmp(), mmap(), munmap(), open(), remove(), and strlen().