CS318 - Pintos: src/tests/userprog/open-bad-ptr.c File Reference
open-bad-ptr.c File Reference
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Passes an invalid pointer to the open system call.
Function Documentation
test_main()
void test_main (void)
Passes an invalid pointer to the open system call.
tests/main.h
The process must be terminated with -1 exit code.
Definition at line 9 of file open-bad-ptr.c.
References fail(), msg(), and open().