CS318 - Pintos: src/userprog/pagedir.h File Reference
pagedir.h File Reference
#include <stdbool.h>
#include <stdint.h>
Functions
uint32_t * pagedir_create (void)
Creates a new page directory that has mappings for kernel virtual addresses, but none for user virtual addresses.
void pagedir_destroy (uint32_t *pd)
Destroys page directory PD, freeing all the pages it references.
bool pagedir_set_page (uint32_t *pd, void *upage, void *kpage, bool rw)
Adds a mapping in page directory PD from user virtual page UPAGE to the physical frame identified by kernel virtual address KPAGE.
void * pagedir_get_page (uint32_t *pd, const void *upage)
Looks up the physical address that corresponds to user virtual address UADDR in PD.
void pagedir_clear_page (uint32_t *pd, void *upage)
Marks user virtual page UPAGE "not present" in page directory PD.
bool pagedir_is_dirty (uint32_t *pd, const void *upage)
Returns true if the PTE for virtual page VPAGE in PD is dirty, that is, if the page has been modified since the PTE was installed.
void pagedir_set_dirty (uint32_t *pd, const void *upage, bool dirty)
Set the dirty bit to DIRTY in the PTE for virtual page VPAGE in PD.
bool pagedir_is_accessed (uint32_t *pd, const void *upage)
Returns true if the PTE for virtual page VPAGE in PD has been accessed recently, that is, between the time the PTE was installed and the last time it was cleared.
void pagedir_set_accessed (uint32_t *pd, const void *upage, bool accessed)
Sets the accessed bit to ACCESSED in the PTE for virtual page VPAGE in PD.
void pagedir_activate (uint32_t *pd)
userprog/pagedir.h
Function Documentation
pagedir_activate()
void pagedir_activate (uint32_t * pd)
userprog/pagedir.h
userprog/pagedir.h
Definition at line 220 of file pagedir.c.
References init_page_dir, NULL, and vtop().
Referenced by invalidate_pagedir(), process_activate(), and process_exit().
pagedir_clear_page()
void pagedir_clear_page (uint32_t * pd, void * upage)
Marks user virtual page UPAGE "not present" in page directory PD.
Later accesses to the page will fault. Other bits in the page table entry are preserved. UPAGE need not be mapped.
Definition at line 144 of file pagedir.c.
References ASSERT, invalidate_pagedir(), is_user_vaddr(), lookup_page(), NULL, pg_ofs(), and PTE_P.
pagedir_create()
uint32_t* pagedir_create (void)
Creates a new page directory that has mappings for kernel virtual addresses, but none for user virtual addresses.
Returns the new page directory, or a null pointer if memory allocation fails.
Definition at line 17 of file pagedir.c.
References init_page_dir, memcpy(), NULL, palloc_get_page(), and PGSIZE.
Referenced by load().
pagedir_destroy()
void pagedir_destroy (uint32_t * pd)
Destroys page directory PD, freeing all the pages it references.
Definition at line 28 of file pagedir.c.
References ASSERT, init_page_dir, NULL, palloc_free_page(), pd_no(), pde_get_pt(), PGSIZE, PHYS_BASE, pte_get_page(), and PTE_P.
Referenced by process_exit().
pagedir_get_page()
void* pagedir_get_page (uint32_t * pd, const void * uaddr)
Looks up the physical address that corresponds to user virtual address UADDR in PD.
Returns the kernel virtual address corresponding to that physical address, or a null pointer if UADDR is unmapped.
Definition at line 126 of file pagedir.c.
References ASSERT, is_user_vaddr(), lookup_page(), NULL, pg_ofs(), pte_get_page(), and PTE_P.
Referenced by install_page().
pagedir_is_accessed()
bool pagedir_is_accessed (uint32_t * pd, const void * vpage)
Returns true if the PTE for virtual page VPAGE in PD has been accessed recently, that is, between the time the PTE was installed and the last time it was cleared.
Returns false if PD contains no PTE for VPAGE.
Definition at line 193 of file pagedir.c.
References lookup_page(), NULL, and PTE_A.
pagedir_is_dirty()
bool pagedir_is_dirty (uint32_t * pd, const void * vpage)
Returns true if the PTE for virtual page VPAGE in PD is dirty, that is, if the page has been modified since the PTE was installed.
Returns false if PD contains no PTE for VPAGE.
Definition at line 164 of file pagedir.c.
References lookup_page(), NULL, and PTE_D.
pagedir_set_accessed()
void pagedir_set_accessed (uint32_t * pd, const void * upage, bool accessed)
Sets the accessed bit to ACCESSED in the PTE for virtual page VPAGE in PD.
Definition at line 202 of file pagedir.c.
References invalidate_pagedir(), lookup_page(), NULL, and PTE_A.
pagedir_set_dirty()
void pagedir_set_dirty (uint32_t * pd, const void * upage, bool dirty)
Set the dirty bit to DIRTY in the PTE for virtual page VPAGE in PD.
Definition at line 173 of file pagedir.c.
References invalidate_pagedir(), lookup_page(), NULL, and PTE_D.
pagedir_set_page()
bool pagedir_set_page (uint32_t * pd, void * upage, void * kpage, bool writable)
Adds a mapping in page directory PD from user virtual page UPAGE to the physical frame identified by kernel virtual address KPAGE.
UPAGE must not already be mapped. KPAGE should probably be a page obtained from the user pool with palloc_get_page(). If WRITABLE is true, the new page is read/write; otherwise it is read-only. Returns true if successful, false if memory allocation failed.
Definition at line 99 of file pagedir.c.
References ASSERT, init_page_dir, init_ram_pages, is_user_vaddr(), lookup_page(), NULL, pg_ofs(), pte_create_user(), PTE_P, PTSHIFT, and vtop().
Referenced by install_page().