CS318 - Pintos: src/tests/threads/priority-condvar.c File Reference
priority-condvar.c File Reference
#include <stdio.h>
#include "tests/threads/tests.h"
#include "threads/init.h"
#include "threads/malloc.h"
#include "threads/synch.h"
#include "threads/thread.h"
#include "devices/timer.h"
Functions
void test_priority_condvar (void)
static void priority_condvar_thread (void *aux UNUSED)
Variables
static thread_func priority_condvar_thread
Tests that cond_signal() wakes up the highest-priority thread waiting in cond_wait().
static struct lock lock
static struct condition condition
Function Documentation
priority_condvar_thread()
static void priority_condvar_thread (void *aux UNUSED) static
Definition at line 46 of file priority-condvar.c.
References cond_wait(), lock_acquire(), lock_release(), msg(), and thread_name().
test_priority_condvar()
void test_priority_condvar (void)
Definition at line 17 of file priority-condvar.c.
References ASSERT, cond_init(), cond_signal(), lock_acquire(), lock_init(), lock_release(), msg(), name, NULL, PRI_DEFAULT, PRI_MIN, priority_condvar_thread, snprintf(), thread_create(), thread_mlfqs, and thread_set_priority().
Variable Documentation
condition
struct condition condition static
Definition at line 14 of file priority-condvar.c.
lock
struct lock lock static
Definition at line 13 of file priority-condvar.c.
Referenced by test_priority_fifo().
priority_condvar_thread
thread_func priority_condvar_thread static
Tests that cond_signal() wakes up the highest-priority thread waiting in cond_wait().
Definition at line 12 of file priority-condvar.c.
Referenced by test_priority_condvar().