CS318 - Pintos: src/tests/threads/priority-donate-lower.c File Reference
priority-donate-lower.c File Reference
#include <stdio.h>
#include "tests/threads/tests.h"
#include "threads/init.h"
#include "threads/synch.h"
#include "threads/thread.h"
Functions
void test_priority_donate_lower (void)
static void acquire_thread_func (void *lock_)
Variables
static thread_func acquire_thread_func
The main thread acquires a lock.
Function Documentation
acquire_thread_func()
static void acquire_thread_func (void * lock_) static
Definition at line 43 of file priority-donate-lower.c.
References lock_acquire(), lock_release(), and msg().
test_priority_donate_lower()
void test_priority_donate_lower (void)
Definition at line 16 of file priority-donate-lower.c.
References acquire_thread_func, ASSERT, lock_acquire(), lock_init(), lock_release(), msg(), PRI_DEFAULT, thread_create(), thread_get_priority(), thread_mlfqs, and thread_set_priority().
Variable Documentation
acquire_thread_func
thread_func acquire_thread_func static
The main thread acquires a lock.
Then it creates a higher-priority thread that blocks acquiring the lock, causing it to donate their priorities to the main thread. The main thread attempts to lower its priority, which should not take effect until the donation is released.
Definition at line 13 of file priority-donate-lower.c.
Referenced by test_priority_donate_lower().