CS318 - Pintos: src/tests/threads/priority-change.c File Reference
priority-change.c File Reference
#include <stdio.h>
#include "tests/threads/tests.h"
#include "threads/init.h"
#include "threads/thread.h"
Functions
void test_priority_change (void)
static void changing_thread (void *aux UNUSED)
Variables
static thread_func changing_thread
Verifies that lowering a thread's priority so that it is no longer the highest-priority thread in the system causes it to yield immediately.
Function Documentation
changing_thread()
static void changing_thread (void *aux UNUSED) static
Definition at line 26 of file priority-change.c.
References msg(), PRI_DEFAULT, and thread_set_priority().
test_priority_change()
void test_priority_change (void)
Definition at line 13 of file priority-change.c.
References ASSERT, changing_thread, msg(), NULL, PRI_DEFAULT, thread_create(), thread_mlfqs, and thread_set_priority().
Variable Documentation
changing_thread
thread_func changing_thread static
Verifies that lowering a thread's priority so that it is no longer the highest-priority thread in the system causes it to yield immediately.
Definition at line 10 of file priority-change.c.
Referenced by test_priority_change().