CS318 - Pintos: src/tests/threads/priority-donate-nest.c File Reference
priority-donate-nest.c File Reference
#include <stdio.h>
#include "tests/threads/tests.h"
#include "threads/init.h"
#include "threads/synch.h"
#include "threads/thread.h"
Data Structures
struct locks
Low-priority main thread L acquires lock A.
Functions
void test_priority_donate_nest (void)
static void medium_thread_func (void *locks_)
static void high_thread_func (void *lock_)
Variables
static thread_func medium_thread_func
static thread_func high_thread_func
Function Documentation
high_thread_func()
static void high_thread_func (void * lock_) static
Definition at line 86 of file priority-donate-nest.c.
References lock_acquire(), lock_release(), and msg().
medium_thread_func()
static void medium_thread_func (void * locks_) static
Definition at line 64 of file priority-donate-nest.c.
References locks::a, locks::b, lock_acquire(), lock_release(), msg(), PRI_DEFAULT, thread_get_priority(), and thread_yield().
test_priority_donate_nest()
void test_priority_donate_nest (void)
Definition at line 28 of file priority-donate-nest.c.
References locks::a, ASSERT, locks::b, high_thread_func, lock_acquire(), lock_init(), lock_release(), medium_thread_func, msg(), PRI_DEFAULT, thread_create(), thread_get_priority(), thread_mlfqs, and thread_yield().
Variable Documentation
high_thread_func
thread_func high_thread_func static
Definition at line 25 of file priority-donate-nest.c.
Referenced by test_priority_donate_nest().
medium_thread_func
thread_func medium_thread_func static
Definition at line 24 of file priority-donate-nest.c.
Referenced by test_priority_donate_nest().