CS318 - Pintos: src/tests/threads/priority-preempt.c File Reference
priority-preempt.c File Reference
#include <stdio.h>
#include "tests/threads/tests.h"
#include "threads/init.h"
#include "threads/synch.h"
#include "threads/thread.h"
Functions
void test_priority_preempt (void)
static void simple_thread_func (void *aux UNUSED)
Variables
static thread_func simple_thread_func
Ensures that a high-priority thread really preempts.
Function Documentation
simple_thread_func()
static void simple_thread_func (void *aux UNUSED) static
Definition at line 31 of file priority-preempt.c.
References msg(), thread_name(), and thread_yield().
test_priority_preempt()
void test_priority_preempt (void)
Definition at line 18 of file priority-preempt.c.
References ASSERT, msg(), NULL, PRI_DEFAULT, simple_thread_func, thread_create(), thread_get_priority(), and thread_mlfqs.
Variable Documentation
simple_thread_func
thread_func simple_thread_func static
Ensures that a high-priority thread really preempts.
Based on a test originally submitted for Stanford's CS 140 in winter 1999 by by Matt Franklin start.nosp@m.led@.nosp@m.lelan.nosp@m.d.st.nosp@m.anfor.nosp@m.d.ed.nosp@m.u, Greg Hutchins gmh@l.nosp@m.elan.nosp@m.d.sta.nosp@m.nfor.nosp@m.d.edu, Yu Ping Hu yph@c.nosp@m.s.st.nosp@m.anfor.nosp@m.d.ed.nosp@m.u. Modified by arens.
Definition at line 15 of file priority-preempt.c.
Referenced by test_priority_preempt().