CS318 - Pintos: src/tests/vm/pt-grow-stack.c File Reference
pt-grow-stack.c File Reference
#include <string.h>
#include "tests/arc4.h"
#include "tests/cksum.h"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Demonstrate that the stack can grow.
Function Documentation
test_main()
void test_main (void)
Demonstrate that the stack can grow.
tests/main.h
This must succeed.
< Save a copy of the stack pointer.
< Move stack pointer to bottom of page.
< Push 32 bytes on stack at once.
< Restore copied stack pointer.
< Tell GCC we destroyed eax.
Definition at line 11 of file pt-grow-stack.c.
References arc4_crypt(), arc4_init(), cksum(), memset(), and msg().