CS318 - Pintos: src/tests/vm/pt-write-code.c File Reference
pt-write-code.c File Reference
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Try to write to the code segment.
Function Documentation
test_main()
void test_main (void)
Try to write to the code segment.
tests/main.h
The process must be terminated with -1 exit code.
< Save a copy of the stack pointer.
< Move stack pointer to bottom of page.
< Push 32 bytes on stack at once.
< Restore copied stack pointer.
< Tell GCC we destroyed eax.
Definition at line 8 of file pt-write-code.c.
References buf, CHECK, CHILD_CNT, close(), create(), exec_children(), fail(), file_name, msg(), open(), random_bytes(), wait_children(), and write().