CS318 - Pintos: src/devices/rtc.h File Reference
rtc.h File Reference
Typedefs
typedef unsigned long time_t
Functions
time_t rtc_get_time (void)
Returns number of seconds since Unix epoch of January 1,.
Typedef Documentation
time_t
typedef unsigned long time_t
Definition at line 4 of file rtc.h.
Function Documentation
rtc_get_time()
time_t rtc_get_time (void)
Returns number of seconds since Unix epoch of January 1,.
Definition at line 43 of file rtc.c.
References bcd_to_bin(), cmos_read(), RTC_REG_HOUR, RTC_REG_MDAY, RTC_REG_MIN, RTC_REG_MON, RTC_REG_SEC, and RTC_REG_YEAR.
Referenced by parse_options().