CS318 - Pintos: src/tests/filesys/seq-test.c File Reference
seq-test.c File Reference
#include "tests/filesys/seq-test.h"
#include <random.h>
#include <syscall.h>
#include "tests/lib.h"
Functions
void seq_test (const char *file_name, void *buf, size_t size, size_t initial_size, size_t(*block_size_func)(void), void(*check_func)(int fd, long ofs))
tests/filesys/seq-test.h
Function Documentation
seq_test()
void seq_test (const char * file_name, void * buf, size_t size, size_t initial_size, size_t(*)(void) block_size_func, void(*)(int fd, long ofs) check_func)
tests/filesys/seq-test.h
Definition at line 7 of file seq-test.c.
References block_size(), buf, CHECK, check_file(), close(), create(), fail(), file_name, msg(), NULL, open(), random_bytes(), and write().
Referenced by test_main().