CS318 - Pintos: src/lib/stdio.h File Reference
stdio.h File Reference
#include <debug.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Macros
#define STDIN_FILENO 0
Include lib/user/stdio.h or lib/kernel/stdio.h, as appropriate.
#define STDOUT_FILENO 1
#define sprintf dont_use_sprintf_use_snprintf
Try to be helpful.
#define vsprintf dont_use_vsprintf_use_vsnprintf
lib/stdio.h
Functions
int printf (const char *,...) PRINTF_FORMAT(1
Standard functions.
int int snprintf (char *, size_t, const char *,...) PRINTF_FORMAT(3
int int int vprintf (const char *, va_list) PRINTF_FORMAT(1
int int int int vsnprintf (char *, size_t, const char *, va_list) PRINTF_FORMAT(3
int int int int int putchar (int)
Writes C to the vga display and serial port.
int puts (const char *)
Writes string S to the console, followed by a new-line character.
void hex_dump (uintptr_t ofs, const void *, size_t size, bool ascii)
Nonstandard functions.
void print_human_readable_size (uint64_t sz)
Prints SIZE, which represents a number of bytes, in a human-readable format, e.g.
void __vprintf (const char *format, va_list args, void(*output)(char, void *), void *aux)
Internal functions.
void __printf (const char *format, void(*output)(char, void *), void *aux,...)
Wrapper for __vprintf() that converts varargs into a va_list.
Macro Definition Documentation
sprintf
#define sprintf dont_use_sprintf_use_snprintf
Try to be helpful.
Definition at line 37 of file stdio.h.
STDIN_FILENO
#define STDIN_FILENO 0
Include lib/user/stdio.h or lib/kernel/stdio.h, as appropriate.
Predefined file handles.
Definition at line 15 of file stdio.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 16 of file stdio.h.
vsprintf
#define vsprintf dont_use_vsprintf_use_vsnprintf
lib/stdio.h
Definition at line 38 of file stdio.h.
Function Documentation
__printf()
void __printf (const char * format, void(*)(char, void *) output, void * aux, ...)
Wrapper for __vprintf() that converts varargs into a va_list.
Definition at line 577 of file stdio.c.
References __vprintf(), va_end, and va_start.
Referenced by __vprintf().
__vprintf()
void __vprintf (const char * format, va_list args, void(*)(char, void *) output, void * aux)
Internal functions.
Definition at line 157 of file stdio.c.
References __printf(), base_d, base_o, base_x, base_X, printf_conversion::CHAR, printf_conversion::flags, format_integer(), format_string(), printf_conversion::INT, printf_conversion::INTMAX, printf_conversion::LONG, printf_conversion::LONGLONG, NOT_REACHED, NULL, parse_conversion(), printf_conversion::precision, PTRDIFF_MAX, printf_conversion::PTRDIFFT, s, printf_conversion::SHORT, SIZE_MAX, printf_conversion::SIZET, strnlen(), printf_conversion::type, and va_arg.
Referenced by __printf(), vhprintf(), vprintf(), and vsnprintf().
hex_dump()
void hex_dump (uintptr_t ofs, const void * buf_, size_t size, bool ascii)
Nonstandard functions.
Nonstandard functions.
Numeric offsets are also included, starting at OFS for the first byte in BUF. If ASCII is true then the corresponding ASCII characters are also rendered alongside.
< Maximum bytes per line.
Definition at line 593 of file stdio.c.
References buf, isprint(), printf(), ROUND_DOWN, and start.
Referenced by bitmap_dump(), compare_bytes(), fsutil_cat(), and main().
print_human_readable_size()
void print_human_readable_size (uint64_t size)
Prints SIZE, which represents a number of bytes, in a human-readable format, e.g.
"256 kB".
Definition at line 642 of file stdio.c.
References NULL, printf(), and PRIu64.
Referenced by block_register(), and identify_ata_device().
printf()
int printf (const char * , ...)
Standard functions.
putchar()
int int int int int putchar (int c)
Writes C to the vga display and serial port.
Writes C to the vga display and serial port.
Definition at line 163 of file console.c.
References acquire_console(), putchar_have_lock(), release_console(), STDOUT_FILENO, and write().
Referenced by fail(), msg(), puts(), and read_line().
puts()
int puts (const char *)
Writes string S to the console, followed by a new-line character.
Definition at line 140 of file console.c.
References acquire_console(), putchar(), putchar_have_lock(), release_console(), s, STDOUT_FILENO, strlen(), and write().
snprintf()
int int snprintf (char * , size_t , const char * , ...)
vprintf()
int int int vprintf (const char * , va_list)
vsnprintf()
int int int int vsnprintf (char * , size_t , const char * , va_list)