CS318 - Pintos: src/tests/filesys/extended/syn-rw.c File Reference
syn-rw.c File Reference
#include <random.h>
#include <syscall.h>
#include "tests/filesys/extended/syn-rw.h"
#include "tests/lib.h"
#include "tests/main.h"
Macros
#define CHILD_CNT 4
Functions
void test_main (void)
tests/main.h
Variables
char buf [BUF_SIZE]
Grows a file in chunks while subprocesses read the growing file.
Macro Definition Documentation
CHILD_CNT
#define CHILD_CNT 4
Definition at line 12 of file syn-rw.c.
Function Documentation
test_main()
void test_main (void)
tests/main.h
tests/main.h
tests/main.h
This must fail, because that directory is non-empty.
tests/main.h
This must fail.
tests/main.h
and an ordinary file in each of them, until we fill up the disk.
Then delete most of them, for two reasons. First, "tar" limits file names to 100 characters (which could be extended to 256 without much trouble). Second, a full disk has no room for the tar archive.
Definition at line 15 of file syn-rw.c.
References buf, BUF_SIZE, CHECK, CHILD_CNT, CHUNK_SIZE, create(), exec_children(), file_name, open(), quiet, random_bytes(), wait_children(), and write().
Variable Documentation
buf
char buf[BUF_SIZE]
Grows a file in chunks while subprocesses read the growing file.
Definition at line 10 of file syn-rw.c.
Referenced by test_main().