CS318 - Pintos: src/tests/threads/tests.c File Reference
tests.c File Reference
#include "tests/threads/tests.h"
#include <debug.h>
#include <string.h>
#include <stdio.h>
Data Structures
struct test
Functions
void run_test (const char *name)
Runs the test named NAME.
void msg (const char *format,...)
Prints FORMAT as if with printf(), prefixing the output by the name of the test and following it with a new-line character.
void fail (const char *format,...)
Prints failure message FORMAT as if with printf(), prefixing the output by the name of the test and FAIL: and following it with a new-line character, and then panics the kernel.
void pass (void)
Prints a message indicating the current test passed.
Variables
static const struct test tests []
static const char * test_name
Function Documentation
fail()
void fail (const char * format, ...)
Prints failure message FORMAT as if with printf(), prefixing the output by the name of the test and FAIL: and following it with a new-line character, and then panics the kernel.
Definition at line 83 of file tests.c.
References exit(), PANIC, printf(), putchar(), test_name, va_end, va_start, vmsg(), and vprintf().
msg()
void msg (const char * format, ...)
Prints FORMAT as if with printf(), prefixing the output by the name of the test and following it with a new-line character.
Definition at line 67 of file tests.c.
References printf(), putchar(), quiet, test_name, va_end, va_start, vmsg(), and vprintf().
Referenced by run_test().
pass()
void pass (void)
Prints a message indicating the current test passed.
tests/threads/tests.h
Definition at line 98 of file tests.c.
References printf(), and test_name.
Referenced by test_alarm_negative(), test_alarm_zero(), and test_mlfqs_load_1().
run_test()
void run_test (const char * name)
Runs the test named NAME.
Definition at line 47 of file tests.c.
References test::function, msg(), test::name, name, PANIC, strcmp(), test_name, and tests.
Referenced by run_task().
Variable Documentation
test_name
const char* test_name static
Definition at line 43 of file tests.c.
Referenced by fail(), msg(), pass(), and run_test().
tests
const struct test tests[] static
Initial value:
=
  {
    {"alarm-single", test_alarm_single},
    {"alarm-multiple", test_alarm_multiple},
    {"alarm-simultaneous", test_alarm_simultaneous},
    {"alarm-priority", test_alarm_priority},
    {"alarm-zero", test_alarm_zero},
    {"alarm-negative", test_alarm_negative},
    {"priority-change", test_priority_change},
    {"priority-donate-one", test_priority_donate_one},
    {"priority-donate-multiple", test_priority_donate_multiple},
    {"priority-donate-multiple2", test_priority_donate_multiple2},
    {"priority-donate-nest", test_priority_donate_nest},
    {"priority-donate-sema", test_priority_donate_sema},
    {"priority-donate-lower", test_priority_donate_lower},
    {"priority-donate-chain", test_priority_donate_chain},
    {"priority-fifo", test_priority_fifo},
    {"priority-preempt", test_priority_preempt},
    {"priority-sema", test_priority_sema},
    {"priority-condvar", test_priority_condvar},
    {"mlfqs-load-1", test_mlfqs_load_1},
    {"mlfqs-load-60", test_mlfqs_load_60},
    {"mlfqs-load-avg", test_mlfqs_load_avg},
    {"mlfqs-recent-1", test_mlfqs_recent_1},
    {"mlfqs-fair-2", test_mlfqs_fair_2},
    {"mlfqs-fair-20", test_mlfqs_fair_20},
    {"mlfqs-nice-2", test_mlfqs_nice_2},
    {"mlfqs-nice-10", test_mlfqs_nice_10},
    {"mlfqs-block", test_mlfqs_block},
  }
Definition at line 12 of file tests.c.
Referenced by run_test().