CS318 - Pintos: src/devices/timer.c File Reference
timer.c File Reference
#include "devices/timer.h"
#include <debug.h>
#include <inttypes.h>
#include <round.h>
#include <stdio.h>
#include "devices/pit.h"
#include "threads/interrupt.h"
#include "threads/synch.h"
#include "threads/thread.h"
Functions
static bool too_many_loops (unsigned loops)
Returns true if LOOPS iterations waits for more than one timer tick, otherwise false.
static void busy_wait (int64_t loops)
Iterates through a simple loop LOOPS times, for implementing brief delays.
static void real_time_sleep (int64_t num, int32_t denom)
Sleep for approximately NUM/DENOM seconds.
static void real_time_delay (int64_t num, int32_t denom)
Busy-wait for approximately NUM/DENOM seconds.
void timer_init (void)
Sets up the timer to interrupt TIMER_FREQ times per second, and registers the corresponding interrupt.
void timer_calibrate (void)
Calibrates loops_per_tick, used to implement brief delays.
int64_t timer_ticks (void)
Returns the number of timer ticks since the OS booted.
int64_t timer_elapsed (int64_t then)
Returns the number of timer ticks elapsed since THEN, which should be a value once returned by timer_ticks().
void timer_sleep (int64_t ticks)
Sleeps for approximately TICKS timer ticks.
void timer_msleep (int64_t ms)
Sleeps for approximately MS milliseconds.
void timer_usleep (int64_t us)
Sleeps for approximately US microseconds.
void timer_nsleep (int64_t ns)
Sleeps for approximately NS nanoseconds.
void timer_mdelay (int64_t ms)
Busy-waits for approximately MS milliseconds.
void timer_udelay (int64_t us)
Sleeps for approximately US microseconds.
void timer_ndelay (int64_t ns)
Sleeps execution for approximately NS nanoseconds.
void timer_print_stats (void)
Prints timer statistics.
static void timer_interrupt (struct intr_frame *args UNUSED)
Timer interrupt handler.
Variables
static int64_t ticks
See [8254] for hardware details of the 8254 timer chip.
static unsigned loops_per_tick
Number of loops per timer tick.
static intr_handler_func timer_interrupt
Function Documentation
busy_wait()
static void NO_INLINE busy_wait (int64_t loops) static
Iterates through a simple loop LOOPS times, for implementing brief delays.
Marked NO_INLINE because code alignment can significantly affect timings, so that if this function was inlined differently in different places the results would be difficult to predict.
Definition at line 204 of file timer.c.
References barrier.
Referenced by real_time_delay(), and too_many_loops().
real_time_delay()
static void real_time_delay (int64_t num, int32_t denom) static
Busy-wait for approximately NUM/DENOM seconds.
Definition at line 240 of file timer.c.
References ASSERT, busy_wait(), loops_per_tick, and TIMER_FREQ.
Referenced by real_time_sleep(), timer_mdelay(), timer_ndelay(), and timer_udelay().
real_time_sleep()
static void real_time_sleep (int64_t num, int32_t denom) static
Sleep for approximately NUM/DENOM seconds.
Definition at line 212 of file timer.c.
References ASSERT, intr_get_level(), INTR_ON, real_time_delay(), ticks, TIMER_FREQ, and timer_sleep().
Referenced by timer_msleep(), timer_nsleep(), and timer_usleep().
timer_calibrate()
void timer_calibrate (void)
Calibrates loops_per_tick, used to implement brief delays.
Definition at line 44 of file timer.c.
References ASSERT, intr_get_level(), INTR_ON, loops_per_tick, printf(), PRIu64, TIMER_FREQ, and too_many_loops().
Referenced by pintos_init().
timer_elapsed()
int64_t timer_elapsed (int64_t then)
Returns the number of timer ticks elapsed since THEN, which should be a value once returned by timer_ticks().
Definition at line 82 of file timer.c.
References timer_ticks().
Referenced by alarm_priority_thread(), block_thread(), load_thread(), test_mlfqs_block(), test_mlfqs_fair(), test_mlfqs_load_1(), test_mlfqs_load_60(), test_mlfqs_load_avg(), test_mlfqs_recent_1(), and timer_sleep().
timer_init()
void timer_init (void)
Sets up the timer to interrupt TIMER_FREQ times per second, and registers the corresponding interrupt.
Definition at line 36 of file timer.c.
References intr_register_ext(), pit_configure_channel(), TIMER_FREQ, and timer_interrupt.
Referenced by pintos_init().
timer_interrupt()
static void timer_interrupt (struct intr_frame *args UNUSED) static
Timer interrupt handler.
Definition at line 171 of file timer.c.
References thread_tick(), and ticks.
timer_mdelay()
void timer_mdelay (int64_t ms)
Busy-waits for approximately MS milliseconds.
Busy waits.
Interrupts need not be turned on.
Busy waiting wastes CPU cycles, and busy waiting with interrupts off for the interval between timer ticks or longer will cause timer ticks to be lost. Thus, use timer_msleep() instead if interrupts are enabled.
Definition at line 131 of file timer.c.
References real_time_delay().
timer_msleep()
void timer_msleep (int64_t ms)
Sleeps for approximately MS milliseconds.
Interrupts must be turned on.
Definition at line 102 of file timer.c.
References real_time_sleep().
Referenced by reset_channel(), speaker_beep(), and wait_while_busy().
timer_ndelay()
void timer_ndelay (int64_t ns)
Sleeps execution for approximately NS nanoseconds.
Interrupts need not be turned on.
Busy waiting wastes CPU cycles, and busy waiting with interrupts off for the interval between timer ticks or longer will cause timer ticks to be lost. Thus, use timer_nsleep() instead if interrupts are enabled.
Definition at line 157 of file timer.c.
References real_time_delay().
timer_nsleep()
void timer_nsleep (int64_t ns)
Sleeps for approximately NS nanoseconds.
Interrupts must be turned on.
Definition at line 118 of file timer.c.
References real_time_sleep().
Referenced by select_device().
timer_print_stats()
void timer_print_stats (void)
Prints timer statistics.
devices/timer.h
Definition at line 164 of file timer.c.
References PRId64, printf(), and timer_ticks().
Referenced by print_stats().
timer_sleep()
void timer_sleep (int64_t ticks)
Sleeps for approximately TICKS timer ticks.
Sleep and yield the CPU to other threads.
Interrupts must be turned on.
Definition at line 90 of file timer.c.
References ASSERT, intr_get_level(), INTR_ON, start, thread_yield(), ticks, timer_elapsed(), and timer_ticks().
Referenced by alarm_priority_thread(), load_thread(), real_time_sleep(), sleeper(), test_alarm_negative(), test_alarm_zero(), test_mlfqs_block(), test_mlfqs_fair(), test_mlfqs_load_1(), test_mlfqs_load_60(), test_mlfqs_load_avg(), test_mlfqs_recent_1(), and test_sleep().
timer_ticks()
int64_t timer_ticks (void)
Returns the number of timer ticks since the OS booted.
Definition at line 71 of file timer.c.
References intr_disable(), intr_set_level(), and ticks.
Referenced by alarm_priority_thread(), block_thread(), load_thread(), sleeper(), test_alarm_priority(), test_mlfqs_block(), test_mlfqs_fair(), test_mlfqs_load_1(), test_mlfqs_load_60(), test_mlfqs_load_avg(), test_mlfqs_recent_1(), test_sleep(), timer_elapsed(), timer_print_stats(), and timer_sleep().
timer_udelay()
void timer_udelay (int64_t us)
Sleeps for approximately US microseconds.
Interrupts need not be turned on.
Busy waiting wastes CPU cycles, and busy waiting with interrupts off for the interval between timer ticks or longer will cause timer ticks to be lost. Thus, use timer_usleep() instead if interrupts are enabled.
Definition at line 144 of file timer.c.
References real_time_delay().
Referenced by shutdown_reboot().
timer_usleep()
void timer_usleep (int64_t us)
Sleeps for approximately US microseconds.
Interrupts must be turned on.
Definition at line 110 of file timer.c.
References real_time_sleep().
Referenced by reset_channel(), and wait_until_idle().
too_many_loops()
static bool too_many_loops (unsigned loops) static
Returns true if LOOPS iterations waits for more than one timer tick, otherwise false.
Definition at line 180 of file timer.c.
References barrier, busy_wait(), start, and ticks.
Referenced by timer_calibrate().
Variable Documentation
loops_per_tick
unsigned loops_per_tick static
Number of loops per timer tick.
Initialized by timer_calibrate().
Definition at line 25 of file timer.c.
Referenced by real_time_delay(), and timer_calibrate().
ticks
int64_t ticks static
See [8254] for hardware details of the 8254 timer chip.
Number of timer ticks since OS booted.
Definition at line 21 of file timer.c.
Referenced by real_time_sleep(), timer_interrupt(), timer_sleep(), timer_ticks(), and too_many_loops().
timer_interrupt
intr_handler_func timer_interrupt static
Definition at line 27 of file timer.c.
Referenced by timer_init().