CS318 - Pintos: src/userprog/tss.c File Reference
tss.c File Reference
#include "userprog/tss.h"
#include <debug.h>
#include <stddef.h>
#include "userprog/gdt.h"
#include "threads/thread.h"
#include "threads/palloc.h"
#include "threads/vaddr.h"
Data Structures
struct tss
The Task-State Segment (TSS).
Functions
void tss_init (void)
Initializes the kernel TSS.
struct tss * tss_get (void)
Returns the kernel TSS.
void tss_update (void)
Sets the ring 0 stack pointer in the TSS to point to the end of the thread stack.
Variables
static struct tss * tss
Kernel TSS.
Function Documentation
tss_get()
struct tss* tss_get (void)
Returns the kernel TSS.
Definition at line 93 of file tss.c.
References ASSERT, NULL, and tss.
Referenced by gdt_init().
tss_init()
void tss_init (void)
Initializes the kernel TSS.
Definition at line 80 of file tss.c.
References tss::bitmap, PAL_ASSERT, PAL_ZERO, palloc_get_page(), SEL_KDSEG, tss::ss0, and tss_update().
Referenced by pintos_init().
tss_update()
void tss_update (void)
Sets the ring 0 stack pointer in the TSS to point to the end of the thread stack.
userprog/tss.h
Definition at line 102 of file tss.c.
References ASSERT, tss::esp0, NULL, PGSIZE, and thread_current().
Referenced by process_activate(), and tss_init().
Variable Documentation
tss
struct tss* tss static
Kernel TSS.
Definition at line 76 of file tss.c.
Referenced by tss_get().