CS318 - Pintos: src/userprog/syscall.h File Reference
syscall.h File Reference
Functions
void syscall_init (void)
userprog/syscall.h
Function Documentation
syscall_init()
void syscall_init (void)
userprog/syscall.h
Definition at line 10 of file syscall.c.
References INTR_ON, intr_register_int(), and syscall_handler().
Referenced by pintos_init().