CS318 - Pintos: src/tests/userprog/write-normal.c File Reference
write-normal.c File Reference
#include <syscall.h>
#include "tests/userprog/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Try writing a file in the most normal way.
Function Documentation
test_main()
void test_main (void)
Try writing a file in the most normal way.
tests/main.h
Definition at line 9 of file write-normal.c.
References byte_cnt(), CHECK, create(), fail(), open(), and write().